// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIIHIiZ0AW1LYRU_U0bvZWIbRNDv6-WVM',
    appId: '1:539980354078:web:d8622efe8217e6fd17940f',
    messagingSenderId: '539980354078',
    projectId: 'dreamapp-project',
    authDomain: 'dreamapp-project.firebaseapp.com',
    storageBucket: 'dreamapp-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx7zqv-rie4_Mi7DITZxJNSrK8Bzftvg0',
    appId: '1:539980354078:android:44f7f7d218f6ee3b17940f',
    messagingSenderId: '539980354078',
    projectId: 'dreamapp-project',
    storageBucket: 'dreamapp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsEGqYh6DMCLcvmBVskhVOsRIyryzV1_I',
    appId: '1:539980354078:ios:69c22a3a49989a2e17940f',
    messagingSenderId: '539980354078',
    projectId: 'dreamapp-project',
    storageBucket: 'dreamapp-project.appspot.com',
    iosClientId: '539980354078-abmta4rq6cvlm2bfsh5ooh7dlijfjvip.apps.googleusercontent.com',
    iosBundleId: 'com.example.dream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsEGqYh6DMCLcvmBVskhVOsRIyryzV1_I',
    appId: '1:539980354078:ios:69c22a3a49989a2e17940f',
    messagingSenderId: '539980354078',
    projectId: 'dreamapp-project',
    storageBucket: 'dreamapp-project.appspot.com',
    iosClientId: '539980354078-abmta4rq6cvlm2bfsh5ooh7dlijfjvip.apps.googleusercontent.com',
    iosBundleId: 'com.example.dream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIIHIiZ0AW1LYRU_U0bvZWIbRNDv6-WVM',
    appId: '1:539980354078:web:ae696c168f3f904517940f',
    messagingSenderId: '539980354078',
    projectId: 'dreamapp-project',
    authDomain: 'dreamapp-project.firebaseapp.com',
    storageBucket: 'dreamapp-project.appspot.com',
  );
}
